name: pet_smart

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.0
  animated_splash_screen: ^1.3.0
  intl: any
  salomon_bottom_bar: ^3.3.2
  table_calendar: ^3.1.1
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  flutter_countdown_timer: ^4.1.0
  font_awesome_flutter: ^10.8.0
  easy_localization: ^3.0.3
  flutter_phoenix: ^1.0.0
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/langs/en.json
    - assets/langs/fil.json
  generate: true
  # Optionally, specify the directory for your ARB files:
  # l10n:
  #   arb-dir: lib/l10n
  #   template-arb-file: app_en.arb
  #   output-localization-file: app_localizations.dart
