name: pet_smart

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.0
  intl: any
  salomon_bottom_bar: ^3.3.2
  table_calendar: ^3.1.1
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  flutter_countdown_timer: ^4.1.0
  font_awesome_flutter: ^10.8.0
  easy_localization: ^3.0.3
  flutter_phoenix: ^1.0.0
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: android/app/src/main/res/mipmap-mdpi/petsmart.png
  color_dark: "#ffffff"
  image_dark: android/app/src/main/res/mipmap-mdpi/petsmart.png
  android_12:
    image: android/app/src/main/res/mipmap-mdpi/petsmart.png
    color: "#ffffff"
    image_dark: android/app/src/main/res/mipmap-mdpi/petsmart.png
    color_dark: "#ffffff"
  web: false

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: assets/langs
  output_dir: lib/generated
  use_deferred_loading: false
